### ISSUE TITLE
Improve Analytics

### ISSUE THREAD

**Issue by dharmesh-hemaram** [Dhruv-Techapps/auto-clicker-auto-fill#407]
Background
- fix the events 
- track error events

TagManager
- remove unwanted tracks
```[tasklist]
### Tasks
- [ ] Utilise Firebase analytics
- [ ] Remove unwanted tracks from [Tag Manager]
- [ ] Track error events [Background]
```

**Comment by dharmesh-hemaram** [comment]
Firebase analytics are supported for chrome extension [firebaseAnalyticsBackground](https://firebase.google.com/docs/web/environments-js-sdk?platform=web)
